### PR TITLE
Changed the underlying method used by the IK solver

### LINKED ISSUE #391: Implementation of PseudoInverse
Which algorithm is the basis for `IKsolver::PseudoInverse`?

In the configuration J.cols() < J.rows() and C==0 the pseudo inverse is computed as:
```C++
Jpinv = inverseSymPosDef(J.transpose() * J + W) * J.transpose();
```

For  W=I (identity) is this supposed to provide the same result as the Moore-Penrose pseudoinverse?

I have a case where `IKsolver` gives me quite small update steps (q_d) for a sparse Jacobian, while Matlab's `pinv()` seems to provide the correct q_d.

### LINKED ISSUE #458: IK/AICO: Retire LAPACK
We rely on f2c'd version of LAPACK for the Cholesky factorisation in IK solver and AICO (coming with two dependencies, `libf2c2-dev` and `liblapack-dev`). This seems to sometimes cause issues w.r.t. performance and numerical stability (or now even throw segmentation faults on Chris' laptop). 

We should:

1. Benchmark the existing performance.
2. Replace with Eigen's symmetric-positive-definite or other linear solvers.
3. If comparable or better performance: replace.

### PR DESCRIPTION
**Pull request by VladimirIvan**
- Retired explicit pseudo-inverse computation, using a linear solver instead (solving for `(SJW)q=y`).
- Retired LAPACK, using `completeOrthogonalDecomposition` when available, `householderQr` otherwise.
- Runtime performance on both LWR and Valkyrie models is the same per single call.
- New solver is more numerically stable.
- Relates to #458 
- Fixes #391

Note:
- Setting C=0 means no regularisation. C=0.9999 (or similar) will regularise by virtually appending a scaled Identity matrix to the Jacobian. Values closer to 1 regularise more. The qNominal is used as a target to move towards for the added rows in the Jacobian. This can be achieved by adding an Identity task map to the problem though (only keeping this for convenience).
- `qNominal` is no longer minimised in the null space (see above).

### CODE REVIEW

File: exotations/solvers/exotica_ik_solver/include/exotica_ik_solver/ik_solver.h [hunk 1]
```diff
@@ -59,15 +56,12 @@ class IKSolver : public MotionSolver, public Instantiable<IKSolverInitializer>
...
-    Eigen::MatrixXd PseudoInverse(Eigen::MatrixXdRefConst J);
     void ScaleToStepSize(Eigen::VectorXdRef xd);
 
     UnconstrainedEndPoseProblem_ptr prob_;  // Shared pointer to the planning problem.
 
-    Eigen::MatrixXd Cinv_;  //!< Weight Matrices
-    Eigen::MatrixXd C_;
-    Eigen::MatrixXd W_;
-    Eigen::MatrixXd Winv_;
+    Eigen::MatrixXd C_;  //!< \brief Regularisation (use values from interval <0, 1))
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/include/exotica_ik_solver/ik_solver.h]: This is wrong Doxygen. Should be `///<` (fixed the same issue yesterday in other places).

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 2]
```diff
@@ -106,16 +72,33 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
 
     if (prob_->N != q0.rows()) throw_named("Wrong size q0 size=" << q0.rows() << ", required size=" << prob_->N);
 
-    const bool UseNullspace = prob_->qNominal.rows() == prob_->N;
+    Eigen::VectorXd qd, qNominal;
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: `q_d`, `q_nominal`

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 3]
```diff
@@ -106,16 +72,33 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
...
+    bool UseNullspace = false;
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: `use_nullspace`

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 4]
```diff
@@ -106,16 +72,33 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
...
+    }
+    else
+    {
+        qNominal = q0;
+    }
 
     solution.resize(1, prob_->N);
 
     Eigen::VectorXd q = q0;
     double error = INFINITY;
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: `std::numeric_limits<double>::infinity()`

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 5]
```diff
@@ -106,16 +72,33 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
...
+    double C = C_(0, 0);
+    Eigen::VectorXd yd;
+    Eigen::MatrixXd J;
+    if (C > 0)
+    {
+        yd = Eigen::VectorXd(prob_->JN + prob_->N);
+        J = Eigen::MatrixXd(prob_->JN + prob_->N, prob_->N);
+    }
     for (int i = 0; i < getNumberOfMaxIterations(); i++)
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: `++i`

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 6]
```diff
@@ -106,16 +72,33 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
...
+    else
+    {
+        qNominal = q0;
+    }
 
     solution.resize(1, prob_->N);
 
     Eigen::VectorXd q = q0;
     double error = INFINITY;
+    double C = C_(0, 0);
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: `const double& C`

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp [hunk 7]
```diff
@@ -128,11 +111,24 @@ void IKSolver::Solve(Eigen::MatrixXd& solution)
...
+        else
+        {
+            yd = prob_->Cost.S * prob_->Cost.ydiff;
+            J = prob_->Cost.S * prob_->Cost.J * W_;
+        }
+
+#if EIGEN_VERSION_AT_LEAST(3, 3, 0)
+        qd = J.completeOrthogonalDecomposition().solve(yd);
+#else
+        qd = J.householderQr().solve(yd);
```
Comment (wxmerkt) [inline exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: Why not the `colPivHouseHolderQr` as used in Levenberg-Marquardt?

File: exotations/solvers/exotica_ik_solver/include/exotica_ik_solver/ik_solver.h (hunk 1 above)
Comment (christian-rauch) [reply exotations/solvers/exotica_ik_solver/include/exotica_ik_solver/ik_solver.h]: This should be fine. I've used similar documentation strings before.
See: http://www.doxygen.nl/manual/docblocks.html (Putting documentation after members
, 3rd box).

**Comment by christian-rauch** [comment]
Why are all these if/then switches for c required? What happends if C = Identity?
I.e. why can we not set matrix `C = I*c` and use it directly for `qd = (J = S * J * W*(1-C)).solve(yd)`?

File: examples/exotica_examples/scripts/example_attach.py [hunk 8]
```diff
@@ -2,15 +2,16 @@
...
+import signal
 
 def handle_attaching(i, x, scene):
     # Update state
     scene.update(x)
     if i == 0:
         # Reset object pose
         scene.attach_object_local(
-            'Item', '', exo.KDLFrame([0.6, -0.3, 0.5, 0, 0, 0, 1]))
+            'Item', '', exo.KDLFrame([0.61, -0.3, 0.5, 0, 0, 0, 1]))
```
[the remark this answers is not in the document]
Comment (VladimirIvan) [reply examples/exotica_examples/scripts/example_attach.py]: Well, I increased Rho=1e3 so now the solver reaches exactly where it's supposed to so the it touches the box on approach. I increased the distance otherwise OMPL start/goal state are invalid.

File: exotations/solvers/exotica_ik_solver/src/ik_solver.cpp (hunk 7 above)
Comment (VladimirIvan) [reply exotations/solvers/exotica_ik_solver/src/ik_solver.cpp]: Sure, for consistency but `fullPivHouseHolderQr` and `householderQr` should be equally good for most problems.

**Comment by VladimirIvan** [comment]
> Why are all these if/then switches for c required? What happends if C = Identity?
> I.e. why can we not set matrix `C = I*c` and use it directly for `qd = (J = S * J * W*(1-C)).solve(yd)`?

If `c>0` then
```
J= ⌈ SJW(1-c) ⌉, yd= ⌈ Sy_diff     ⌉
   ⌊ Ic       ⌋      ⌊ q-q_nominal ⌋ 
```
This is a hack to get the solution to scale down `SJW` by `1-c` while scaling up the the bottom part of `J`. This way `c` will blend between minimising the cost (`y_diff`) and minimising the distance to nominal pose. This will also add non-zero elements into `J` so singular problems will be biased towards `q_nominal`. The regularised pseudo-inverse handled this better (without adding `Ic` into `J`) but it was also less stable because of explicit computation of `Jinv`. If there is a better way to achieve this regularisation I'm happy to use that.

If `c<=0`, `C` is completely dropped from the equation for performance.

What you propose (without the if-s) would only scale down the J, it wouldn't add non-zero elements into it. I keep that scaling (`SJW(1-c)`) so that you have some notion what value of `c` to choose (e.g., between 0 and 1). It's still not perfect because when Rho (and S) are high, `c` also has to be scaled to achieve the same regularisation (e.g., Rho=1 >> c= 0.9, Rho=1e-3, c=0.999). This wasn't the case with the pseudo-inverse.

**Comment by wxmerkt** [comment]
Actually, while we are updating it: @VladimirIvan could you please add some doxygen to the header? About the implementation, with references, etc.

**Comment by wxmerkt** [comment]
This is a very positive change performance-wise:

On my Valkyrie whole-body IK benchmark:

- Before this change: ~200ms
- After this change: ~40ms
